version: '3'
services:
  api:
    build: ./api
    networks:
      - lufthansa_project
    # ports:
    #   - "8030:8030"
  dash:
    build: ./dash
    ports:
      - "8050:8050" # host_port:docker_port
    networks:
      - lufthansa_project
    # environment:
    #   - FAST_API_URL=http://api:8030/
    depends_on:
      - api

networks:
  lufthansa_project:
