version: '3.8'
services:
  api:
    build: ./api
    networks:
      - backend
    ports:
      - "8030:8030"
  dash:
    build: ./dash
    ports:
      - "8050:8050" # host_port:docker_port
    networks:
      - backend
    environment:
      - FAST_API_URL=http://localhost:8030/
    depends_on:
      - api

networks:
  backend


